[workspace]
members = ["rs/ic_auth_types", "rs/ic_auth_verifier"]
resolver = "2"

[workspace.package]
version = "0.4.8"
edition = "2024"
repository = "https://github.com/ldclabs/ic-auth"
keywords = ["auth", "identity", "deeplink", "icp", "canister"]
description = "ğŸ” The Internet Computer identity based web authentication."
categories = ["web-programming"]
license = "MIT"

[workspace.dependencies]
arc-swap = "1.7"
base64 = "0.22"
candid = "0.10"
ciborium = "0.2"
hex = "0.4"
http = "1.3"
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
serde_json = "1"
k256 = { version = "0.13" }
p256 = { version = "0.13" }
ed25519-dalek = "2"
ed25519-consensus = "2.1"
rand = "0.9"
sha2 = "0.10"
sha3 = "0.10"
ic-canister-sig-creation = "1.3"
ic-signature-verification = "0.2"
ic-agent = "0.40"
simple_asn1 = "0.6"
xid = "1.1"
url = "2.5"
